server:
  port: 80


eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
  instance:
    instance-id: orderConsumer80
    #    访问路径可以显示ip地址
    prefer-ip-address: true


spring:
  application:
    name: cloud-order-service